
export const flightData = [
  {
    id: 1,
    airline: "US-Bangla Airlines",
    airlineCode: "BS",
    logo: "https://airlines-resources.s3.ap-southeast-1.amazonaws.com/icon/BS.png",
    from: {
      city: "Dhaka",
      airport: "Hazrat Shahjalal International Airport",
      code: "DAC",
      time: "07:45",
      date: "Sun, 08 Mar 2026",
    },
    to: {
      city: "Cox's Bazar",
      airport: "Cox's Bazar Airport",
      code: "CXB",
      time: "08:50",
      date: "Sun, 08 Mar 2026",
    },
    duration: "1H 5M",
    stops: 0,
    stopLabel: "Direct Flight",
    price: 4846.47,
    originalPrice: 5049,
    baggage: "20 kg",
    class: "Economy",
    departureSlot: "morning", // 7AM-12PM
    arrivalSlot: "morning",
  },
  {
    id: 2,
    airline: "US-Bangla Airlines",
    airlineCode: "BS",
    logo: "https://airlines-resources.s3.ap-southeast-1.amazonaws.com/icon/BS.png",
    from: {
      city: "Dhaka",
      airport: "Hazrat Shahjalal International Airport",
      code: "DAC",
      time: "11:55",
      date: "Sun, 08 Mar 2026",
    },
    to: {
      city: "Cox's Bazar",
      airport: "Cox's Bazar Airport",
      code: "CXB",
      time: "13:00",
      date: "Sun, 08 Mar 2026",
    },
    duration: "1H 5M",
    stops: 0,
    stopLabel: "Direct Flight",
    price: 4846.47,
    originalPrice: 5049,
    baggage: "20 kg",
    class: "Economy",
    departureSlot: "morning",
    arrivalSlot: "afternoon",
  },
  {
    id: 3,
    airline: "US-Bangla Airlines",
    airlineCode: "BS",
    logo: "https://airlines-resources.s3.ap-southeast-1.amazonaws.com/icon/BS.png",
    from: {
      city: "Dhaka",
      airport: "Hazrat Shahjalal International Airport",
      code: "DAC",
      time: "15:05",
      date: "Sun, 08 Mar 2026",
    },
    to: {
      city: "Cox's Bazar",
      airport: "Cox's Bazar Airport",
      code: "CXB",
      time: "16:10",
      date: "Sun, 08 Mar 2026",
    },
    duration: "1H 5M",
    stops: 0,
    stopLabel: "Direct Flight",
    price: 4846.47,
    originalPrice: 5049,
    baggage: "20 kg",
    class: "Economy",
    departureSlot: "afternoon",
    arrivalSlot: "evening",
  },
  {
    id: 4,
    airline: "US-Bangla Airlines",
    airlineCode: "BS",
    logo: "https://airlines-resources.s3.ap-southeast-1.amazonaws.com/icon/BS.png",
    from: {
      city: "Dhaka",
      airport: "Hazrat Shahjalal International Airport",
      code: "DAC",
      time: "19:00",
      date: "Sun, 08 Mar 2026",
    },
    to: {
      city: "Cox's Bazar",
      airport: "Cox's Bazar Airport",
      code: "CXB",
      time: "20:05",
      date: "Sun, 08 Mar 2026",
    },
    duration: "1H 5M",
    stops: 0,
    stopLabel: "Direct Flight",
    price: 4846.47,
    originalPrice: 5049,
    baggage: "20 kg",
    class: "Economy",
    departureSlot: "evening",
    arrivalSlot: "evening",
  },
  {
    id: 5,
    airline: "US-Bangla Airlines",
    airlineCode: "BS",
    logo: "https://airlines-resources.s3.ap-southeast-1.amazonaws.com/icon/BS.png",
    from: {
      city: "Dhaka",
      airport: "Hazrat Shahjalal International Airport",
      code: "DAC",
      time: "07:45",
      date: "Sun, 08 Mar 2026",
    },
    to: {
      city: "Cox's Bazar",
      airport: "Cox's Bazar Airport",
      code: "CXB",
      time: "08:50",
      date: "Sun, 08 Mar 2026",
    },
    duration: "1H 5M",
    stops: 0,
    stopLabel: "Direct Flight",
    price: 6152.67,
    originalPrice: 6449,
    baggage: "20 kg",
    class: "Business",
    departureSlot: "morning",
    arrivalSlot: "morning",
  },
  {
    id: 6,
    airline: "Biman Bangladesh",
    airlineCode: "BG",
    logo: "https://airlines-resources.s3.ap-southeast-1.amazonaws.com/icon/BG.png",
    from: {
      city: "Dhaka",
      airport: "Hazrat Shahjalal International Airport",
      code: "DAC",
      time: "06:00",
      date: "Sun, 08 Mar 2026",
    },
    to: {
      city: "Cox's Bazar",
      airport: "Cox's Bazar Airport",
      code: "CXB",
      time: "07:10",
      date: "Sun, 08 Mar 2026",
    },
    duration: "1H 10M",
    stops: 0,
    stopLabel: "Direct Flight",
    price: 5200.0,
    originalPrice: 5500,
    baggage: "20 kg",
    class: "Economy",
    departureSlot: "earlyMorning",
    arrivalSlot: "morning",
  },
  {
    id: 7,
    airline: "Novoair",
    airlineCode: "VQ",
    logo: "https://airlines-resources.s3.ap-southeast-1.amazonaws.com/icon/VQ.png",
    from: {
      city: "Dhaka",
      airport: "Hazrat Shahjalal International Airport",
      code: "DAC",
      time: "09:30",
      date: "Sun, 08 Mar 2026",
    },
    to: {
      city: "Cox's Bazar",
      airport: "Cox's Bazar Airport",
      code: "CXB",
      time: "10:40",
      date: "Sun, 08 Mar 2026",
    },
    duration: "1H 10M",
    stops: 1,
    stopLabel: "1 Stop",
    price: 3999.0,
    originalPrice: 4200,
    baggage: "20 kg",
    class: "Economy",
    departureSlot: "morning",
    arrivalSlot: "morning",
  },
  {
    id: 8,
    airline: "Novoair",
    airlineCode: "VQ",
    logo: "https://airlines-resources.s3.ap-southeast-1.amazonaws.com/icon/VQ.png",
    from: {
      city: "Dhaka",
      airport: "Hazrat Shahjalal International Airport",
      code: "DAC",
      time: "22:00",
      date: "Sun, 08 Mar 2026",
    },
    to: {
      city: "Cox's Bazar",
      airport: "Cox's Bazar Airport",
      code: "CXB",
      time: "23:10",
      date: "Sun, 08 Mar 2026",
    },
    duration: "1H 10M",
    stops: 0,
    stopLabel: "Direct Flight",
    price: 4500.0,
    originalPrice: 4800,
    baggage: "20 kg",
    class: "Economy",
    departureSlot: "night",
    arrivalSlot: "night",
  },
];

export const timeSlots = [
  { value: "earlyMorning", label: "Early Morning", range: "3AM - 7AM" },
  { value: "morning", label: "Morning", range: "7AM - 12PM" },
  { value: "afternoon", label: "Afternoon", range: "12PM - 4PM" },
  { value: "evening", label: "Evening", range: "4PM - 9PM" },
  { value: "night", label: "Night", range: "9PM - 12AM" },
  { value: "midnight", label: "Midnight", range: "12AM - 3AM" },
];

export const airlines = [
  { value: "US-Bangla Airlines", label: "US-Bangla Airlines" },
  { value: "Biman Bangladesh", label: "Biman Bangladesh" },
  { value: "Novoair", label: "Novoair" },
];
