export const airports = [
  {
    code: "DAC",
    city: "Dhaka",
    country: "Bangladesh",
    name: "Hazrat Shahjalal Intl",
  },
  {
    code: "CGP",
    city: "Chittagong",
    country: "Bangladesh",
    name: "Shah Amanat Intl",
  },
  { code: "ZYL", city: "Sylhet", country: "Bangladesh", name: "Osmani Intl" },
  { code: "DXB", city: "Dubai", country: "UAE", name: "Dubai Intl Airport" },
  {
    code: "AUH",
    city: "Abu Dhabi",
    country: "UAE",
    name: "Zayed Intl Airport",
  },
  {
    code: "RUH",
    city: "Riyadh",
    country: "Saudi Arabia",
    name: "King Khalid Intl",
  },
  {
    code: "JED",
    city: "Jeddah",
    country: "Saudi Arabia",
    name: "King Abdulaziz Intl",
  },
  {
    code: "MED",
    city: "Madinah",
    country: "Saudi Arabia",
    name: "Mohammad Bin Abdulaziz",
  },
  { code: "DOH", city: "Doha", country: "Qatar", name: "Hamad Intl Airport" },
  {
    code: "KWI",
    city: "Kuwait City",
    country: "Kuwait",
    name: "Kuwait Intl Airport",
  },
  { code: "KUL", city: "Kuala Lumpur", country: "Malaysia", name: "KLIA" },
  {
    code: "SIN",
    city: "Singapore",
    country: "Singapore",
    name: "Changi Airport",
  },
  {
    code: "BKK",
    city: "Bangkok",
    country: "Thailand",
    name: "Suvarnabhumi Airport",
  },
  {
    code: "DEL",
    city: "New Delhi",
    country: "India",
    name: "Indira Gandhi Intl",
  },
  {
    code: "BOM",
    city: "Mumbai",
    country: "India",
    name: "Chhatrapati Shivaji Intl",
  },
  {
    code: "CMB",
    city: "Colombo",
    country: "Sri Lanka",
    name: "Bandaranaike Intl",
  },
  { code: "KTM", city: "Kathmandu", country: "Nepal", name: "Tribhuvan Intl" },
  { code: "LHR", city: "London", country: "UK", name: "Heathrow Airport" },
  { code: "CDG", city: "Paris", country: "France", name: "Charles de Gaulle" },
  {
    code: "JFK",
    city: "New York",
    country: "USA",
    name: "John F. Kennedy Intl",
  },
  { code: "YYZ", city: "Toronto", country: "Canada", name: "Pearson Intl" },
  {
    code: "SYD",
    city: "Sydney",
    country: "Australia",
    name: "Kingsford Smith",
  },
];
